[CLB-22] Show/Hide AddNewSkill modal done
q-praksa/collaborator pull request #19
Opened 2021-12-30 19:48 UTC by rocky1207

2021-12-31 08:01 UTC, kimnovak requested changes

2021-12-31 08:01 UTC, kimnovak commented on src/redux/reducers/modalReducer.tsx
> +const modalReducer = (state = initialState, action: Action) => {
We will have different types of Modals in the app, so a modal type should be added to the state

2021-12-31 08:01 UTC, kimnovak commented on src/redux/actions/actionTypes.ts
>  };
OPEN and CLOSE are a bit too generic, can you rename it to OPEN_MODAL and CLOSE_MODAL?

2021-12-31 08:01 UTC, kimnovak commented on src/redux/actions/counter.ts
> +};
You should create a modal.ts file inside this folder and move these 2 actions there

2021-12-31 08:01 UTC, kimnovak commented on src/redux/reducers/modalReducer.tsx
> +            return Object.assign({}, state);
Shorter / easier syntax that doesn't mutate the state
```suggestion
            return {
                ...state,
                show: true
            }
```

2021-12-31 08:01 UTC, kimnovak commented on src/redux/reducers/modalReducer.tsx
> +            return Object.assign({}, state);
```suggestion
            return {
                 ...state,
                 show: false
             }
```

2021-12-31 08:09 UTC, kimnovak commented
Can you also copy the package-lock.json we have here: https://raw.githubusercontent.com/q-praksa/collaborator/development/package-lock.json and paste it inside your local package-lock.json, and add to commit to avoid the conflicts

2022-01-04 11:12 UTC, vukstojanovic approved these changes

2022-01-04 22:26 UTC, SreckoStojic approved these changes
Great job!

2022-01-05 07:23 UTC, merged