[CLB-21]Test PR
q-praksa/collaborator pull request #24
Opened 2022-01-04 10:48 UTC by Zola987

2022-01-04 11:37 UTC, Mbotunjac approved these changes

2022-01-04 11:37 UTC, Mbotunjac commented
looks good

2022-01-04 17:22 UTC, kimnovak requested changes

2022-01-04 17:22 UTC, kimnovak commented on src/App.tsx
> +                />
```suggestion
                <Route
                    path="/header"
                    element={
                        <ProtectedRoute>
                             <PrivateRoute>
                                 <Header />
                            </PrivateRoute>
                        </ProtectedRoute>
                    }
                />
```

2022-01-04 17:22 UTC, kimnovak commented on src/App.tsx
> +                />
```suggestion
                <Route
                    path="/"
                    element={
                        <ProtectedRoute>
                            <PrivateRoute>
                                <Home />
                            </PrivateRoute>
                        </ProtectedRoute>
                    }
                />
```

2022-01-04 17:22 UTC, kimnovak commented on src/App.tsx
>                  <Route path="/testss" element={<TestSS />} />
```suggestion
                <Route path="/testss" element={<TestSS />} />
                <Route
                    path="/timesheet"
                    element={
                        <ProtectedRoute>
                            <Timesheet />
                        </ProtectedRoute>
                     }
                 />
```

2022-01-04 17:22 UTC, kimnovak commented on src/components/Login/index.tsx
> +        console.log(details);
```suggestion
```

2022-01-04 17:22 UTC, kimnovak commented on src/components/Login/index.tsx
> +            console.log('logged in');
```suggestion
```

2022-01-04 17:22 UTC, kimnovak commented on src/components/Login/index.tsx
> +            console.log('logged in');
```suggestion
```

2022-01-04 17:22 UTC, kimnovak commented on src/App.tsx
> +
```suggestion
```

2022-01-04 17:22 UTC, kimnovak commented on src/components/Login/index.tsx
> +        login(details);
after logging in we should redirect the user to the homepage
You can achieve it by adding this at the top of this component
```
const navigate = useNavigate();
```
and then calling `navigate('/')` after login

2022-01-04 17:22 UTC, kimnovak commented on src/pages/TestBB.tsx
> +            {/* <Timesheet /> */}
```suggestion
```

2022-01-04 17:22 UTC, kimnovak commented on src/redux/actions/actionTypes.ts
> +export default actionTypes;
src/redux got renamed to src/reduxStore, you should delete the old directory

2022-01-04 17:22 UTC, kimnovak commented on src/redux/reducers/index.ts
> +export type RootState = ReturnType<typeof allReducers>;
src/redux got renamed to src/reduxStore, you should delete the old directory

2022-01-04 17:22 UTC, kimnovak commented on src/redux/store/store.ts
> +export default store;
src/redux got renamed to src/reduxStore, you should delete the old directory

2022-01-05 08:43 UTC, Zola987 commented on src/App.tsx
>                  <Route path="/testss" element={<TestSS />} />
I put test page, for Admin check

2022-01-05 10:24 UTC, merged